### ISSUE TITLE
Build the project locally

### ISSUE THREAD

**Issue by MokhFn** [Blockchain-Technology-Lab/consensus-decentralization#112]
When running the [data collection script](https://github.com/Blockchain-Technology-Lab/consensus-decentralization/blob/main/consensus_decentralization/collect_data.py) an error is raised : 
```Traceback (most recent call last):
  File "/consensus-decentralization/consensus_decentralization/collect_data.py", line 16, in <module>
    from consensus_decentralization.helper import ROOT_DIR, RAW_DATA_DIR
ModuleNotFoundError: No module named 'consensus_decentralization'
```

I guess it's because we need to build the project locally first, so that packages and their directories are locally known ? If so, don't we need a setup.py/setup.cfg configuration file ?

**Comment by LadyChristina** [comment]
From which directory did you run the script? Could you please try the following from the root directory and let me know if it works? 
`python -m consensus_decentralization.collect_data`

**Comment by MokhFn** [comment]
I ran it from the root dir, as per the docs : 
```
python collect_data.py
```
Running your command works like a charm.
