### ISSUE TITLE
Specify which ledger to collect data for

### ISSUE THREAD

**Issue by MokhFn** [Blockchain-Technology-Lab/consensus-decentralization#113]
When running the data collection script, it can be useful to be able to specify which ledger to collect data for (without having to comment/uncomment quesries from the queries yaml file).
An additional argument to the script could be the solution.

**Comment by LadyChristina** [comment]
Sounds like a good idea to me, thanks for the suggestion. Feel free to implement it if you want, otherwise Dimitris or I will pick it up when we have time
