### ISSUE TITLE
Fix flags in the 'How to use' doc

### ISSUE THREAD

**Issue by MokhFn** [Blockchain-Technology-Lab/consensus-decentralization#114]
The how to use doc specifies the following for the animated tag : 

![image](https://github.com/Blockchain-Technology-Lab/consensus-decentralization/assets/20328292/26b4a283-6e61-4c81-adda-e3dd1a96cecc)

**Comment by LadyChristina** [comment]
Hi @MokhFn, if you are referring to the lack of bullet points, there was already an issue raised about it (#109) which gets fixed by my latest PR (#123). If you had any other concerns about the flags, could you please elaborate? Otherwise, I think we can close this issue.
