### ISSUE TITLE
BigQuery Cardano Dataset stuck at 2023-06

### ISSUE THREAD

**Issue by MokhFn** [Blockchain-Technology-Lab/consensus-decentralization#116]
Not sure if this is an issue and if the Dataset maintenance should be your responsibility (or the community's).
The Dataset for Cardano unfortunately has data only up to 2023-06.

**Comment by LadyChristina** [comment]
Thanks for bringing this to our attention, we might update the sample data files at some point to bring them up to date. However, please note that, as stated in the documentation, they are just _sample_ files, so we do not promise that they will be updated regularly. We have plans to change the way we retrieve block data, but for now if anyone needs to run the tool with up-to-date data, we would encourage them to get the data directly from [BigQuery](https://console.cloud.google.com/bigquery), using the queries described [here](https://blockchain-technology-lab.github.io/consensus-decentralization/data/).
