### ISSUE TITLE
For relevant metrics, take into account the Cloud Providers and other entities

### ISSUE THREAD

**Issue by MokhFn** [Blockchain-Technology-Lab/consensus-decentralization#118]
Cloud providers, Synthetic platforms (Like Lido & Co), hardware providers (ASIC, NVIDIA, etc ...) do centralize the block production don't they ?
If so, i think it's relevant to take these into account when computing the different metrics, like Nakamoto.
But this is beyond technical, more like a research that spills into the tool later on.

**Comment by dimkarakostas** [comment]
Yes, this would be an analysis for another layer, e.g. network or hardware. This has been discussed on the research side [here](https://arxiv.org/pdf/2211.01291.pdf), so we'll keep this repository focused on consensus and release other tools for other layer analyses.

**Comment by MokhFn** [comment]
Understood, thanks for clarifying
