### ISSUE TITLE
Tezos latest data is from 2022

### ISSUE THREAD

**Issue by songproducer** [Blockchain-Technology-Lab/consensus-decentralization#142]
Seems the Tezos data feed isn't working.

**Comment by LadyChristina** [comment]
We are currently getting Tezos data from BigQuery and that dataset only includes data up to 2022. You can see for youself if you query the data here: https://console.cloud.google.com/marketplace/product/public-data-finance/crypto-tezos-dataset. 
We do plan to source the data from our own full nodes in the future, but until we do that, there's not much we can do if the data is not updated on BigQuery, so I'll go ahead and close this issue
