### ISSUE TITLE
Support custom timeframe

### ISSUE THREAD

**Issue by dimkarakostas** [Blockchain-Technology-Lab/consensus-decentralization#29]

**Comment by MokhFn** [comment]
Is this about being able to provide a timeframe range ? instead of the current static value format (year or month or day, or every month since 2010)
If not, i'll create a new issue for that.

**Comment by dimkarakostas** [comment]
Yes, that's what this task is about. The user should be able to specify a range and a granularity (day/month/year) and run the tool on this timeframe.

**Comment by MokhFn** [comment]
Okay thanks for clarifying.
